### ISSUE TITLE
Dependency specification in current master is wrong (probably failed automatic merge)

### ISSUE THREAD

**Issue by burnpanck** [hgrecco/pint-pandas#188]
Installing `pint_pandas` from the current master will not install neither `pint` nor `pandas`. The relevant subsection of `pyproject.toml` is as follows:
```toml
[project]
name = "Pint-Pandas"
requires-python = ">=3.9"
# ...

[tool.setuptools.package-data]
pint_pandas = [
      "py.typed"
      ]
dependencies = [
  "pint>=0.21",
  "pandas>=1.5"
]

# ...
```

I'm pretty sure the `dependencies` key was never meant to be found under `[tool.setuptools.package-data]` but instead under `[project]`.
